### ISSUE TITLE
 Web UI strips newlines from global variable default values when populated at lower scopes

### ISSUE THREAD

**Issue by westbywest** [Scalr/scalr#80]
I encountered this issue on Scalr v 5.11.22 while creating a global variable for YAML content:
![default](https://cloud.githubusercontent.com/assets/947189/19316312/994a3864-9066-11e6-87e5-f91132055397.png)

If I then want to override that variable at the farm or server scope, the default value turns into this:
![lower-scope](https://cloud.githubusercontent.com/assets/947189/19316326/a699e258-9066-11e6-8d92-cd017f4614f4.png)

The global-scope default value does render correctly on launched servers, i.e. szradm queryenv list-global-variables displays this:

```
<variable name="CUSTOM_YAML" private="0">---
blah: blahblah
blah2: blah2blah2
blah3:
  blah3.1:
   blah3.1.1: blah3.1.1_value</variable>
```

So, the web UI is stripping newlines when it populates default values for global variables at lower scopes.  This appears to not effect the values actually passed for those variables to launched servers, _unless_ someone unwittingly saves the default value when overriding that variable at farm or server scope.
